repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [ --exit-non-zero-on-fix ]
        types_or: [ python, pyi, jupyter ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        # Run on whole project, not just updated files.
        # See pyproject.toml config for which files mypy will type check.
        pass_filenames: false
        # This hook runs in an isolated environment.
        # All dependencies that mypy needs to analyze during type checking should
        # be re-specified here.
        additional_dependencies: [ numpy ]
        # Override the default args, which includes --ignore-missing-imports
        args: [ ]


  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args: [ --max-size=25k ]  # TODO: settle on allowable output size
